############################################################################
#                               Restart
############################################################################
spring:
  devtools:
    restart:
      enabled: true